name = "lenient_parse"
version = "1.0.0"

description = "Lenient parse functions for Gleam."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "lenient_parse" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
