name = "pilkku"
version = "1.0.0"
gleam = ">= 1.5.0"

description = "Arbitrary precision decimal arithmetic for Gleam"
licences = ["Apache-2.0"]
repository = { type = "forgejo", user = "Nicd", repo = "pilkku", host = "git.ahlcode.fi" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
bigi = ">= 3.2.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
