name: test

on:
    push:
        branches:
            - master
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: erlef/setup-beam@v1
              with:
                  otp-version: "27.2.0"
                  gleam-version: "1.7.0"
                  rebar3-version: "3"
            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"
            - run: gleam deps download
            - name: Run JavaScript tests
              run: gleam test --target javascript
            - name: Run Erlang tests
              run: gleam test --target erlang
            - run: gleam format --check src test
