name: test

on:
    push:
        branches:
            - master
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: erlef/setup-beam@v1
              with:
                  otp-version: "26.0.2"
                  gleam-version: "1.5.0"
                  rebar3-version: "3"
                  # elixir-version: "1.15.4"
            - name: Set up uv
              uses: astral-sh/setup-uv@f3bcaebff5eace81a1c062af9f9011aae482ca9d # v3
              with:
                  version: "latest"
                  enable-cache: true
            - run: gleam deps download
            - run: gleam test
            - run: gleam format --check src test
